version: "3.8"

services:
  harmony-app:
    build: .
    container_name: harmony-music-app
    ports:
      - "5173:5173"
    stdin_open: true # Equivalent à -i (interactif)
    tty: true # Equivalent à -t (terminal)
    volumes:
      - .:/app # Synchronise le code local avec le container
      - /app/node_modules # Volume anonyme pour node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Améliore le hot reload
    restart: unless-stopped # Redémarre automatiquement si crash
  db:
    image: mariadb
    restart: always
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: harmony
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080